skills_list = [
    'python', 
    'sql', 
    'aws',
    'amazon web services',
    'etl',
    'extract',
    'transform', 
    'load', 
    'warehousing', 
    'modeling', 
    'integration', 
    'pipelines', 
    'big data technologies',
    'hadoop',
    'spark', 
    'distributed computing', 
    'machine learning', 
    'deep learning', 
    'natural language processing',
    'nlp', 
    'visualization', 
    'etl',
    'nifi', 
    'informatica', 
    'dms',
    'postgresql',
    'mysql',
    'oracle', 
    'nosql',
    'mongodb', 
    'cassandra', 
    'data governance', 
    'data quality management', 
    'streaming data processing', 
    'kafka', 
    'containerization',
    'docker',
    'kubernetes', 
    'infrastructure as code',
    'terraform', 
    'cloudformation)', 
    'version control',
    'git',
    'github',
    'gitlab', 
    'continuous integration / continuous deployment',
    'ci/cd', 
    'linux',
    'unix', 
    'scripting',
    'bash', 
    'powershell', 
    'security', 
    'encryption', 
    'privacy regulations', 
    'airflow', 
    'google cloud platform',
    'gcp', 
    'azure', 
    'devops methodologies', 
    'agile methodologies', 
    'scrum', 
    'jira', 
    'collaboration',
    'slack',
    'microsoft teams', 
    'problem-solving', 
    'critical thinking', 
    'analytical', 
    'communication', 
    'teamwork',
    'engineering',
    'analysis',
    'science',
    'programming',
    'data manipulation',
    'cloud computing',
    'shell scripting',
    'storage',
    'querying',
    'architecture',
    'cleansing',
    'transformation',
    'preprocessing',
    'aggregation',
    'mining',
    'exploration',
    'validation',
    'wrangling',
    'migration',
    'replication',
    'governance',
    'ethics',
    'lineage',
    'catalog',
    'lakes',
    'streams',
    'ingestion',
    'exhaust',
    'backup',
    'recovery',
    'synchronization',
    'retention',
    'versioning',
    'compression',
    'deduplication',
    'anonymization',
    'visualization',
    'storytelling',
    'interpretation',
    'insight',
    'strategy',
    'roadmap',
    'governance',
    'stewardship',
    'standards',
    'compliance',
    'security',
    'access control',
    'classification',
    'protection',
    'privacy',
    'anonymization',
    'masking',
    'obfuscation',
    'pseudonymization',
    'lineage',
    'provenance',
    'lifecycle',
    'retention',
    'disposal',
    'quality',
    'profiling',
    'cleansing',
    'validation',
    'enrichment',
    'completeness',
    'accuracy',
    'consistency',
    'integrity',
    'timeliness',
    'relevancy',
    'duplication',
    'redundancy',
    'normalization',
    'denormalization',
    'architecture',
    'modeling',
    'schema',
    'dictionary',
    'flow',
    'lineage',
    'catalog',
    'lake',
    'warehouse',
    'mart',
    'pipeline',
    'stream',
    'ingestion',
    'extraction',
    'transformation',
    'loading',
    'synchronization',
    'replication',
    'migration',
    'archival',
    'retrieval',
    'access',
    'security',
    'privacy',
    'protection',
    'governance',
    'stewardship',
    'compliance',
    'regulation',
    'standardization',
    'quality',
    'cleansing',
    'profiling',
    'validation',
    'enrichment',
    'monitoring',
    'governance',
    'lineage',
    'provenance',
    'audit',
    'discovery',
    'classification',
    'tagging',
    'management',
    'strategy',
    'governance',
    'science',
    'analysis',
    'analytics',
    'visualization',
    'business intelligence',
    'business analytics',
    'big data',
    'machine learning',
    'deep learning',
    'natural language processing',
    'predictive analytics',
    'prescriptive analytics',
    'descriptive analytics',
    'mining',
    'exploration',
    'preprocessing',
    'cleaning',
    'transformation',
    'wrangling',
    'munging',
    'integration',
    'modeling',
    'architecture',
    'governance',
    'quality',
    'stewardship',
    'security',
    'privacy',
    'cloud computing',
    'distributed computing',
    'parallel computing',
    'scalability',
    'reliability',
    'availability',
    'fault tolerance',
    'high availability',
    'redundancy',
    'load balancing',
    'elasticity',
    'resilience',
    'containerization',
    'docker',
    'kubernetes',
    'microservices',
    'serverless computing',
    'infrastructure as code',
    'continuous integration',
    'continuous delivery',
    'continuous deployment',
    'agile methodology',
    'scrum',
    'kanban',
    'lean',
    'devops',
    'collaboration tools',
    'version control',
    'git',
    'github',
    'gitlab',
    'bitbucket',
    'jenkins',
    'circleci',
    'travis ci',
    'teamcity',
    'jira',
    'confluence',
    'slack',
    'microsoft teams',
    'communication skills',
    'interpersonal skills',
    'presentation skills',
    'problem-solving skills',
    'critical thinking',
    'analytical skills',
    'attention to detail',
    'time management',
    'project management',
    'leadership',
    'mentoring',
    'training',
    'documentation',
    'reporting',
    'technical writing',
    'client management',
    'requirements gathering',
    'stakeholder management',
    'customer service',
    'business acumen',
    'domain knowledge',
    'industry knowledge',
    'data ethics',
    'legal compliance',
    'regulatory compliance',
    'data regulation',
    'regulation',
    'data protection laws',
    'gdpr',
    'protection',
    'ccpa',
    'hipaa',
    'sox',
    'data security',
    'network security',
    'cybersecurity',
    'encryption',
    'access control',
    'authentication',
    'authorization',
    'security policies',
    'security protocols',
    'penetration testing',
    'vulnerability assessment',
    'incident response',
    'data breach',
    'security awareness',
    'risk management',
    'compliance auditing',
    'security monitoring',
    'security operations',
    'security governance',
    'security architecture',
    'security standards',
    'security frameworks',
    'visualization',
    'graphical representation',
    'charting',
    'dashboards',
    'interactive visualization',
    'tableau',
    'power bi',
    'matplotlib',
    'seaborn',
    'plotly',
    'd3.js',
    'bokeh',
    'qlikview',
    'looker',
    'storytelling',
    'narrative visualization',
    'data-driven storytelling',
    'data interpretation',
    'interpretation',
    'insight extraction',
    'trend analysis',
    'pattern recognition',
    'correlation analysis',
    'regression analysis',
    'classification analysis',
    'cluster analysis',
    'time series analysis',
    'anomaly detection',
    'root cause analysis',
    'predictive modeling',
    'forecasting',
    'prescriptive modeling',
    'optimization modeling',
    'optimisation modeling',
    'simulation modeling',
    'monte carlo simulation',
    'agent-based modeling',
    'machine learning algorithms',
    'supervised learning',
    'unsupervised learning',
    'semi-supervised learning',
    'reinforcement learning',
    'classification algorithms',
    'regression algorithms',
    'clustering algorithms',
    'dimensionality reduction',
    'feature selection',
    'ensemble learning',
    'neural networks',
    'deep learning algorithms',
    'convolutional neural networks',
    'recurrent neural networks',
    'long short-term memory networks',
    'generative adversarial networks',
    'transformers',
    'natural language processing',
    'tokenization',
    'lemmatization',
    'stemming',
    'part-of-speech tagging',
    'named entity recognition',
    'sentence segmentation',
    'text classification',
    'sentiment analysis',
    'topic modeling',
    'entity extraction',
    'word embeddings',
    'sequence-to-sequence models',
    'attention mechanisms',
    'machine translation',
    'question answering',
    'summarization',
    'dialogue systems',
    'information retrieval',
    'information extraction',
    'text generation',
    'text-to-speech synthesis',
    'speech recognition',
    'speaker diarization',
    'automatic speech recognition',
    'voice activity detection',
    'speaker recognition',
    'audio processing',
    'image processing',
    'computer vision algorithms',
    'object detection',
    'object recognition',
    'object tracking',
    'image segmentation',
    'image classification',
    'image generation',
    'image captioning',
    'style transfer',
    'deep reinforcement learning',
    'recommender systems',
    'collaborative filtering',
    'content based filtering',
    'hybrid recommender',
    'knowledge-based recommender',
    'context-aware recommender',
    'matrix factorization',
    'association rule learning',
    'market basket analysis',
    'user segmentation',
    'customer segmentation',
    'churn prediction',
    'customer lifetime value prediction',
    'market basket analysis',
    'market segmentation',
    'sales forecasting',
    'demand forecasting',
    'pricing optimization',
    'recommendation engines',
    'personalization',
    'customer analytics',
    'customer insights',
    'user behavior analysis',
    'social network analysis',
    'graph analytics',
    'link analysis',
    'network analysis',
    'centrality analysis',
    'community detection',
    'homophily analysis',
    'influence analysis',
    'virality analysis',
    'sentiment analysis',
    'opinion mining',
    'emotion detection',
    'aspect-based sentiment analysis',
    'multimodal sentiment analysis',
    'irony detection',
    'sarcasm detection',
    'fake news detection',
    'hate speech detection',
    'bias detection',
    'stereotype detection',
    'toxicity detection',
    'abuse detection',
    'profanity detection',
    'cyberbullying detection',
    'offensive language detection',
    'inappropriate content detection',
    'misinformation detection',
    'disinformation detection',
    'rumor detection',
    'conspiracy theory detection',
    'data preprocessing',
    'cleaning',
    'transformation',
    'normalization',
    'standardization',
    'scaling',
    'feature engineering',
    'feature extraction',
    'missing data imputation',
    'outlier detection',
    'anomaly detection',
    'noise reduction',
    'data augmentation',
    'data synthesis',
    'data anonymization',
    'data obfuscation',
    'data perturbation',
    'data shuffling',
    'data masking',
    'data tokenization',
    'data encryption',
    'data compression',
    'data deduplication',
    'data hashing',
    'data anonymization techniques',
    'k-anonymity',
    'l-diversity',
    't-closeness',
    'differential privacy',
    'generalization',
    'suppression',
    'perturbation',
    'microaggregation',
    'k-means clustering',
    'hierarchical clustering',
    'density based clustering',
    'expectation maximization'
    'em',
    'principal component analysis',
    'pca',
    'singular value decomposition',
    'svd',
    'independent component analysis',
    'ica',
    'linear discriminant analysis',
    'lda',
    'non-negative matrix factorization',
    'nmf',
    't-distributed stochastic neighbor embedding',
    't-sne',
    'autoencoder',
    'variational autoencoder',
    'vae',
    'generative adversarial network'
    'gan',
    'sequence-to-sequence (seq2seq) model',
    'encoder-decoder architecture',
    'attention mechanism',
    'transformer architecture',
    'bert',
    'bidirectional encoder representations from transformers',
    'gpt',
    'generative pre-trained transformer',
    'roberta',
    'robustly optimized bert approach',
    'albert',
    'argo',
    'orchestration',
    'dag',
    'kubeflow',
    'xlnet',
    'generalized autoregressive pretraining for language understanding',
    'electra',
    'efficiently learning an encoder that classifies token replacements accurately'
    'bart',
    'bidirectional and auto-regressive transformers',
    't5',
    'text-to-text transfer transformer',
    'multimodal models',
    'multimodal fusion',
    'multimodal learning',
    'fusion architectures',
    'early fusion',
    'late fusion',
    'deep fusion',
    'attention fusion',
    'transformer fusion',
    'multimodal embeddings',
    'cross-modal retrieval',
    'cross-modal generation',
    'audio-visual models',
    'audio-text models',
    'text-visual models',
    'zero-shot learning',
    'few-shot learning',
    'one-shot learning',
    'meta-learning',
    'transfer learning',
    'self-supervised learning',
    'semi-supervised learning',
    'weakly-supervised learning',
    'self-attention mechanism',
    'multi-head attention',
    'masked language modeling',
    'sequence classification',
    'sequence generation',
    'sequence labeling',
    'sequence translation',
    'sequence summarization',
    'sequence completion',
    'sequence matching',
    'sequence regression',
    'sequence prediction',
    'sequence alignment',
    'sequence segmentation',
    'sequence clustering',
    'sequence ranking',
    'sequence tagging',
    'sequence recognition',
    'sequence parsing',
    'sequence understanding',
    'sequence comprehension',
    'sequence inference',
    'sequence evaluation',
    'sequence optimization',
    'sequence decision making',
    'sequence generation',
    'sequence transformation',
    'sequence manipulation',
    'sequence processing',
    'sequence interpretation',
    'sequence reasoning',
    'sequence prediction',
    'sequence forecasting',
    'sequence simulation',
    'sequence modeling',
    'sequence learning',
    'sequence adaptation',
    'sequence discovery',
    'bi',
    'powerbi',
    'databricks',
    'c++',
    'c++,',
    'java',
    'azure',
    'scala',
    'spark',
    'devops',
    'c#',
    'c#,',
    'gke',
    'iac',
    'c'
    

    ]